//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turns
    {
        public long TurnID { get; set; }
        public Nullable<long> GamePartID { get; set; }
        public string PawnListStr { get; set; }
        public string TurnColor { get; set; }
        public Nullable<int> WhiteScore { get; set; }
        public Nullable<int> BlackScore { get; set; }
        public Nullable<int> BestCurrentBlowScore { get; set; }
        public string BestMove { get; set; }
        public Nullable<System.DateTime> InserionDateTime { get; set; }
        public string BestPositionsFor { get; set; }
        public Nullable<int> BestPositionsWeight { get; set; }
    
        public virtual GamePart GamePart { get; set; }
    }
}
