//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBestPostions
    {
        public string PawnListStr { get; set; }
        public string BestPositionsFor { get; set; }
        public Nullable<int> BestPositionsWeight { get; set; }
        public long TurnID { get; set; }
        public string GamePartMode { get; set; }
    }
}
